export interface Orders {
  id: string | null;
  order_number: string;
  customer_id: string;
  shipping_company_name: string | null;
  shipping_address_1: string;
  shipping_address_2: string | null;
  shipping_city: string;
  shipping_state: string;
  shipping_postal_code: string;
  shipping_country: string;
  shipping_phone: string | null;
  billing_company_name: string | null;
  billing_address_1: string | null;
  billing_address_2: string | null;
  billing_city: string | null;
  billing_state: string | null;
  billing_postal_code: string | null;
  billing_country: string | null;
  subtotal: number;
  shipping_cost: number | null;
  tax_amount: number | null;
  discount_amount: number | null;
  total_amount: number;
  status: string | null;
  payment_status: string | null;
  payment_method: string | null;
  payment_due_date: Date | null;
  order_date: Date;
  ship_date: Date | null;
  delivery_date: Date | null;
  cancelled_date: Date | null;
  tracking_number: string | null;
  carrier: string | null;
  internal_notes: string | null;
  customer_notes: string | null;
  created_at: Date | null;
  updated_at: Date | null;
}